language: python
dist: "xenial"
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coverage
  - pip install .[test]

script: python -m yafowil.tests.__init__
after_success:
  - bin/coverage run --source src/yafowil src/yafowil/tests/__init__.py
  - bin/coverage report
  - bin/coverage html
